par(mfcol=c(2,2))
plot(y$DateTime, y$Global_active_power, type='l', ylab="Global Active Power", xlab="")
plot(y$DateTime, y$Sub_metering_1, type='l', ylab ="Energy sub metering", xlab="")
lines(y$DateTime, y$Sub_metering_2, type='l', col='red')
lines(y$DateTime, y$Sub_metering_3, type='l', col='blue')
legend('topright', c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1,1), col=c("black","red","blue"))
plot(y$DateTime, y$Voltage, type='l', ylab="Voltage", xlab="datetime")
plot(y$DateTime, y$Global_reactive_power, type='l', ylab="Global_reactive_power", xlab="datetime")
